name: Linting and Testing

on:
  push:
    branches: [develop, main]

concurrency:
  group: lint-and-test-${{ github.ref }}-${{ github.run_id }}

jobs:
  push_to_registry:
    name: Build and deploy
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ingeniumconnect/wheelswise-frontend
      IMAGE_TAG: ${{ github.ref == 'refs/heads/develop' && 'uat-latest' || 'prod-latest' }}
      ENVIRONMENT_NAME: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}  # develop->dev, main->prod

    environment:
      name: ${{ env.ENVIRONMENT_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_PUBLIC_DNS }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            set -e

            sudo docker stop ${{ secrets.APP_NAME }} || true
            sudo docker rm ${{ secrets.APP_NAME }} || true

            sudo docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            sudo docker image prune -a -f || true

            sudo docker run -d \
              --name ${{ secrets.APP_NAME }} \
              --restart unless-stopped \
              -p ${{ secrets.PORT }} \
              --env-file ${{ secrets.ENV_FILE_PATH }} \
              ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
